apps/billing/urls.py
from django.urls import path
from . import views

app_name = 'billing'

urlpatterns = [
    path('', views.BillingListView.as_view(), name='index'),

]

apps/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('apps.menu.urls')),  # account/だったら　account.urlsを参照しなさい。
    path('account/', include('apps.account.urls')),  # account/だったら　account.urlsを参照しなさい。
    path('lesson/', include('apps.lesson.urls')),
    path('billing/', include('apps.billing.urls')),
    path('report/', include('apps.report.urls')),
    path('admin/', admin.site.urls)
]

apps/billing/models.py
from django.db import models

# Create your models here.

apps/billing/forms.py
from datetime import datetime

from dateutil import parser
from dateutil.relativedelta import relativedelta
from django import forms
from django.utils import timezone


def create_month_choices():
    choices = []
    for i in range(0, 1+3):
        base_date = timezone.localdate() - relativedelta(months=i)
        choices.append((datetime.strftime(base_date, "%Y/%m"), datetime.strftime(base_date, "%Y/%m")))
    return choices


class SearchForm(forms.Form):
    """ ここで請求月のフォームを作っている
    """

    billing_yyyymm = forms.ChoiceField(choices=create_month_choices, label="請求月", required=False)

    def clean_billing_yyyymm(self):

        billing_yyyymm = self.cleaned_data["billing_yyyymm"]
        if billing_yyyymm:

            return parser.parse(billing_yyyymm).date()

apps/billing/views.py
from django.utils import timezone
from django.views import generic

from apps.account.models import Account
from apps.lesson.models import Lesson
from .aggregator import Aggregator
from .api import get_genre_data
from .forms import SearchForm


class BillingListView(generic.ListView):
    model = Account
    template_name = "billing/billing_list.html"

    def create_account_lesson_log_list(self):
        form = SearchForm(self.request.GET)
        form.is_valid()

        billing_yyyymm = form.cleaned_data['billing_yyyymm']

        if not billing_yyyymm:
            billing_yyyymm = timezone.localdate()

        lesson_log_list = Lesson.objects.filter(attending_date__year=billing_yyyymm.year,
                                                attending_date__month=billing_yyyymm.month).select_related('account', 'genre')

        genre_dict = get_genre_data()
        aggregate = Aggregator()
        billing_result_list = aggregate.get_monthly_billings(Account.objects.all(), lesson_log_list, genre_dict)

        return billing_result_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = SearchForm(self.request.GET)

        context["aggregate_result"] = self.create_account_lesson_log_list()

        return context

templates/billing/billing_list.html
{% extends "base.html" %}

{% block title %}
    請求一覧
{% endblock title %}

{% block main %}
    <h1>請求一覧</h1>
    <form method="get" action="{% url 'billing:index' %}">
        {{ form }}
        <input type="submit" value="ボタンを押す">
    </form>
    <table border="1" width="80%" name="accounts_list">
        <tr align="center">
            <th>顧客ID</th>
            <th>顧客名</th>
            <th>ジャンル</th>
            <th>合計レッスン数</th>
            <th>請求金額</th>
        </tr>
        {% for billing in aggregate_result %}
            <tr>
                <td>{{ billing.account_id }}</td>
                <td>{{ billing.account_name }}</td>
                <td>{{ billing.genre_names }}{{ billing.genre_num }}</td>
                <td>{{ billing.attend_num }}レッスン</td>
                <td>{{ billing.total_billing }}円</td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}