apps/lesson/urls.py
from django.urls import path
from . import views

app_name = 'lesson'

urlpatterns = [
    path('', views.LessonListView.as_view(), name='index'),
    path('create', views.LessonCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.LessonUpdateView.as_view(), name='update'),
]

apps/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('apps.menu.urls')),  # account/だったら　account.urlsを参照しなさい。
    path('account/', include('apps.account.urls')),  # account/だったら　account.urlsを参照しなさい。
    path('lesson/', include('apps.lesson.urls')),
    path('billing/', include('apps.billing.urls')),
    path('report/', include('apps.report.urls')),
    path('admin/', admin.site.urls)
]

apps/lesson/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils import timezone

from apps.account.models import Account


class Genre(models.Model):
    """ 新規登録時に必要なモデル。
    """
    name = models.CharField('ジャンル名', max_length=50, unique=True)
    basic_rate = models.IntegerField('基本料金')
    created_at = models.DateTimeField('作成日時', default=timezone.now)
    updated_at = models.DateTimeField('更新日時', auto_now=True)

    def __str__(self):
        return self.name


""" account,genreは第一引数に'名前'を入れると引数が複数あるとエラーがでてしまうため、後ろにverbose_name=''
    をつけて記述するとエラーがでなくなる。
"""


class Lesson(models.Model):
    """ 一覧表示用のモデル。
    """
    account = models.ForeignKey(Account, on_delete=models.CASCADE, verbose_name='受講者')  # モデル同士の紐付け"ForeignKey"
    genre = models.ForeignKey(Genre, on_delete=models.PROTECT, verbose_name='ジャンル')
    attending_hour = models.IntegerField('受講時間', validators=[MinValueValidator(1), MaxValueValidator(12)])
    attending_date = models.DateField('受講日')
    created_at = models.DateTimeField('作成日時', auto_now_add=True)
    updated_at = models.DateTimeField('更新日時', auto_now=True)

    def __str__(self):
        return str(self.genre.name)

    def payment(self):
        measured_rate = 0

        if self.genre.name == "英語":
            measured_rate = self.genre.basic_rate + self.attending_hour * 3500

        if self.genre.name == "ファイナンス":
            if 20 > self.attending_hour:
                measured_rate = 3300 * self.attending_hour + self.genre.basic_rate
            elif 50 > self.attending_hour >= 20:
                measured_rate = 3300 * 20 + 2800 * (self.attending_hour - 20)
            elif self.attending_hour >= 50:
                measured_rate = 3300 * 20 + 2500 * 30 + 2500 * (self.attending_hour - 50)

        if self.genre.name == "プログラミング":

            if self.attending_hour < 5:
                measured_rate = self.genre.basic_rate
            elif 20 > self.attending_hour >= 5:
                measured_rate = self.genre.basic_rate + 3500 * (self.attending_hour - 5)
            elif 35 > self.attending_hour >= 20:
                measured_rate = self.genre.basic_rate + 0 * 5 + 3500 * 15 + 3000 * (self.attending_hour - 20)
            elif 50 > self.attending_hour >= 35:
                measured_rate = self.genre.basic_rate + 0 * 5 + 3500 * 15 + 2800 * 15 + 2800 * (self.attending_hour - 35)
            elif self.attending_hour >= 50:
                measured_rate = self.genre.basic_rate + 0 * 5 + 3500 * 15 + 2800 * 15 + 2500 * 15 + 2500 * (self.attending_hour - 50)

        return measured_rate

apps/lesson/views.py
from django.urls import reverse_lazy
from django.views import generic

from apps.lesson.models import Lesson


class LessonListView(generic.ListView):
    model = Lesson
    template_name = "lesson/lesson_list.html"
    queryset = Lesson.objects.select_related("account", "genre")


class LessonCreateView(generic.CreateView):
    model = Lesson
    template_name = "lesson/lesson_create.html"
    fields = ("account", "genre", "attending_date", "attending_hour")
    success_url = reverse_lazy("lesson:index")

    def form_invalid(self, form):
        res = super().form_invalid(form)
        res.status_code = 400
        return res


class LessonUpdateView(generic.UpdateView):
    model = Lesson
    template_name = "lesson/lesson_update.html"
    fields = ("account", "genre", "attending_date", "attending_hour")
    success_url = reverse_lazy("lesson:index")

    def form_invalid(self, form):
        res = super().form_invalid(form)
        res.status_code = 400
        return res

templates/lesson/lesson_create.html
{% extends "base.html" %}

{% block title %}
    レッスン 新規追加
{% endblock title %}

{% block main %}

    <h2>レッスン受講記録</h2>
    <form method="post">
        {% csrf_token %}

        {{ form.as_p }}

        <input type="submit" value="登録">
    </form>

{% endblock %}

templates/lesson/lesson_list.html
{% extends "base.html" %}


{% block title %}
    レッスン受講記録一覧
{% endblock title %}


{% block main %}
{% if lesson_list %}
    <h1>レッスン受講記録一覧</h1>
    <table border="1" width="80%" name="accounts_list">
        <tr>
            <th>ID</th>
            <th>受講者</th>
            <th>ジャンル</th>
            <th>受講日</th>
            <th>受講時間</th>
            <th>支払い金額</th>
            <th></th>
        </tr>
        {% for lesson in lesson_list %}
            <tr>
                <td>{{ lesson.id }}</td>
                <td>{{ lesson.account }}</td>
                <td>{{ lesson.genre }}</td>
                <td>{{ lesson.attending_date }}</td>
                <td>{{ lesson.attending_hour }} h</td>
                <td>{{ lesson.payment }}</td>
                <td><a href="{% url 'lesson:update' lesson.id %}">編集</a></td>
            </tr>
        {% endfor %}

    </table>
    <a href="{% url 'lesson:create' %}">新規追加</a>
{% else %}
    <p>受講履歴がありません</p>
{% endif %}
{% endblock %}

templates/lesson/lesson_update.html
{% extends "base.html" %}

{% block title %}
    編集
{% endblock title %}

{% block main %}

    <h2>受講記録編集</h2>
    <form method="post">
        {% csrf_token %}

        {{ form.as_p }}

        <input type="submit" value="登録">
    </form>

{% endblock %}