apps/report/urls.py
from django.urls import path
from . import views

app_name = 'report'

urlpatterns = [
    path('', views.ReportListView.as_view(), name='index'),
]

apps/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('apps.menu.urls')),  # account/だったら　account.urlsを参照しなさい。
    path('account/', include('apps.account.urls')),  # account/だったら　account.urlsを参照しなさい。
    path('lesson/', include('apps.lesson.urls')),
    path('billing/', include('apps.billing.urls')),
    path('report/', include('apps.report.urls')),
    path('admin/', admin.site.urls)
]

apps/report/models.py
from django.db import models

# Create your models here.

apps/report/forms.py
from datetime import datetime

from dateutil import parser
from dateutil.relativedelta import relativedelta
from django import forms
from django.utils import timezone


def create_month_choices():
    choices = []
    for i in range(0, 1+3):
        base_date = timezone.localdate() - relativedelta(months=i)
        choices.append((datetime.strftime(base_date, "%Y/%m"), datetime.strftime(base_date, "%Y/%m")))
    return choices


class SearchForm(forms.Form):
    """ ここでレポートのフォームを作っている
    """
    billing_yyyymm = forms.ChoiceField(choices=create_month_choices, label="請求月", required=False)

    def clean_billing_yyyymm(self):

        billing_yyyymm = self.cleaned_data["billing_yyyymm"]
        if billing_yyyymm:

            return parser.parse(billing_yyyymm).date()

apps/report/views.py
from django.utils import timezone
from django.views import generic

from apps.account.models import Account
from apps.billing.api import get_genre_data, create_target_queryset_dict
from apps.report.forms import SearchForm
from .aggregator import ReportAggregator


class ReportListView(generic.ListView):
    model = Account
    template_name = "report/report_list.html"

    def create_report_list(self):
        form = SearchForm(self.request.GET)
        form.is_valid()

        billing_yyyymm = form.cleaned_data['billing_yyyymm']

        if not billing_yyyymm:
            billing_yyyymm = timezone.localdate()
        billing_yyyy, billing_mm = billing_yyyymm.year, billing_yyyymm.month

        query_dict = create_target_queryset_dict(billing_yyyy, billing_mm)

        genre_dict = get_genre_data()

        genre_gender_aggregate = ReportAggregator()
        lesson_gender_analysis_result = genre_gender_aggregate.analye_genre_gender_trend(query_dict, genre_dict)

        genre_age_aggregate = ReportAggregator()
        lesson_age_analysis_result = genre_age_aggregate.analye_age_group_gender_trend(query_dict, genre_dict)

        return lesson_gender_analysis_result, lesson_age_analysis_result

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["form"] = SearchForm(self.request.GET)
        context["lesson_gender_analysis_result"], context["lesson_age_analysis_result"] = self.create_report_list()

        return context

templates/report/report_list.html
{% extends "base.html" %}

{% block title %}
    レポート
{% endblock title %}

{% block main %}
    <h1>レポート</h1>
    <form method="get" , action="{% url 'report:index' %}">
        {{ form }}
        <input type="submit" value="ボタンを押す">
    </form>
    <h2>ジャンルと性別別</h2>
    <table border="1" width="80%" name="accounts_list">
        <tr align="center">
            <th>ジャンル</th>
            <th>性別</th>
            <th>レッスン数</th>
            <th>受講者数</th>
            <th>売り上げ</th>
        </tr>
        {% for report in lesson_gender_analysis_result %}
            <tr>
                <td>{{ report.genre_name }}</td>
                <td>{{ report.gender_name }}</td>
                <td>{{ report.lesson_num }}</td>
                <td>{{ report.account_num }}人</td>
                <td>{{ report.sales }}</td>
            </tr>
        {% endfor %}
    </table>


    <h2>ジャンルと年齢層別</h2>
    <table border="1" width="80%" name="accounts_list">
        <tr align="center">
            <th>ジャンル</th>
            <th>性別</th>
            <th>年齢層別</th>
            <th>レッスン数</th>
            <th>受講者数</th>
            <th>売り上げ</th>
        </tr>
        {% for report in lesson_age_analysis_result %}
            <tr>
                <td>{{ report.genre_name }}</td>
                <td>{{ report.gender_name }}</td>
                <td>{{ report.age_group }}</td>
                <td>{{ report.lesson_num }}</td>
                <td>{{ report.account_num }}人</td>
                <td>{{ report.sales }}</td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}